name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 

    - name: Downcase Image Tag
      id: image-tag
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ github.repository }}

    - name: Build and push
      id: docker-build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile.devenv
        no-cache: true
        push: true
        tags: ${{ steps.image-tag.outputs.lowercase }}:latest

    - name: Print image url
      run: echo "Image pushed to:\n${{ steps.docker-build.outputs.metadata }}"
      
